#!/bin/bash

# UTILS

function print_error() {
    echo -e "Git Hook Error: $1"
}

function get_repo_root_path() {
    local repository_root_path=$(git rev-parse --show-toplevel)
    repository_root_path="${repository_root_path,,}" # convert path to lowercase
    repository_root_path=$(echo "/$repository_root_path" | sed 's/://') # replace C:/ with /c/ on windows
    echo "$repository_root_path"
}

# CHECK DEFINITIONS

function check_gitmoji() {
    local commit_msg=$1
    local repository_root_path=$(get_repo_root_path)
    local gitmoji_list_file="$repository_root_path/.githooks/.gitmoji_list.txt"

    mapfile -t gitmoji_list < "$gitmoji_list_file"

    for emoji in "${gitmoji_list[@]}"; do
        emoji=${emoji//:/}
        if [[ "$commit_msg" == *"$emoji"* ]]; then
            exit 0
        fi
    done

    print_error "Commit message must start with a gitmoji followed by whitespace."
    exit 1
}

# CHECK EXECUTION

commit_msg=$(<"$1")

check_gitmoji "$commit_msg"
