#!/bin/bash

# UTILS

function print_error() {
    echo -e "Git Hook Error: $1"
}

function get_repo_root_path() {
    local repository_root_path=$(git rev-parse --show-toplevel)
    repository_root_path="${repository_root_path,,}" # convert path to lowercase
    repository_root_path=$(echo "/$repository_root_path" | sed 's/://') # replace C:/ with /c/ on windows
    echo "$repository_root_path"
}

# CHECK DEFINITIONS

function check_gitmoji() {
    local commit_msg=$1
    local repository_root_path=$(get_repo_root_path)

    # Create temporary files to store the Gitmoji list
    local gitmoji_spec=$(mktemp)
    trap 'rm -f "$gitmoji_spec"' EXIT
    local gitmoji_list_file=$(mktemp)
    trap 'rm -f "$gitmoji_list_file"' EXIT


    # Download the Gitmoji list into the temporary file
    curl -s https://gitmoji.dev/api/gitmojis > "$gitmoji_spec"
    cat "$gitmoji_spec" \
    | sed -E 's/,/,\n/g' \
    | grep -E '"emoji":|"code":' \
    | sed -E 's/.*:\"(.+)\",$/\1/' > "$gitmoji_list_file"

    $repository_root_path/.scripts/ensure_commit_starts_with_gitmoji.sh "$commit_msg" "$gitmoji_list_file"

    if [[ $? -ne 0 ]]; then
        print_error "Commit message must start with a gitmoji followed by whitespace: '$commit_msg'"
        exit 1
    fi
}

# CHECK EXECUTION

commit_msg=$(<"$1")

check_gitmoji "$commit_msg"
