#version 450

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

// Structures of memory operations
struct CopyRangeOperation
{
    uint startIndex;
    uint endIndex;
    uint destinationIndex;
};

struct InvalidateRangeOperation
{
    uint startIndex;
    uint endIndex;
};

// SSBO to be modified
struct QuadInstanceData
{
    uint color;
    float position[2];
    float scale[2];
    uint rotation_texIndex;
};

layout(std430, binding = 0) buffer QuadInstanceStorageBlock
{
    QuadInstanceData quads[]; // Change the type as per your instance data
};

// Staging SSBO
layout(std430, binding = 1) buffer StagingBuffer
{
    uint staging_data[];
};

// Helper functions applying operations
void applyCopyRangeOperation(CopyRangeOperation crop)
{
    for (uint j = crop.startIndex; j < crop.endIndex; j++) {
        uint dest = crop.destinationIndex + (j - crop.startIndex);
        quads[dest] = quads[j];
    }
}

void applyInvalidateRangeOperation(InvalidateRangeOperation irop)
{
    for (uint j = irop.startIndex; j < irop.endIndex; j++) {
        quads[j].color = 0;
    }
}

void main()
{
    const uint op_count = staging_data[0];
    uint op_id_cursor = 1;
    uint current_memory_cursor = 1 + op_count;

    for (uint i = 0; i < op_count; i++) {
        const uint op_id = staging_data[op_id_cursor++];
        if (op_id == 1) // copy-range op
        {
            const CopyRangeOperation crop = CopyRangeOperation(
                staging_data[current_memory_cursor++],
                staging_data[current_memory_cursor++],
                staging_data[current_memory_cursor++]
            );

            applyCopyRangeOperation(crop);
        }
        else if (op_id == 2) // invalidate-range op
        {
            const InvalidateRangeOperation irop = InvalidateRangeOperation(
                staging_data[current_memory_cursor++],
                staging_data[current_memory_cursor++]
            );

            applyInvalidateRangeOperation(irop);
        }
    }
}
