[engine]
; Use OpenGL for rendering. Currently only OpenGL is supported.
UseOpenGL = true

; Logging level in the engine.
; Possible values are: trace, debug, info, warning, error, critical, off.
LogLevel = info

####################################################################################################

[app.window]

; Windowing mode.
; Possible values are: windowed, fullscreen, borderless.
Mode = windowed

; Vertical sync. If true, the application will refresh the screen at the same rate as the monitor.
; Possible values are: true, false.
UseVSync = true

; Resolution of the window.
; If the mode is set to windowed, the window size will be the same as resolution.
; If the resolution is not supported by the monitor, the engine will try to find the closest
;   resolution.
;
; Most common values are:
;   3840x2160 for 4K
;   2560x1440 for 2K
;   1920x1080
;   1280x720
Resolution = 1600x900
