name: Prepare environment
description: Install build dependencies

runs:
  using: "composite"
  steps:
    - name: Checkout submodules
      # Checkout has to be done manually because the `actions/checkout` action does not support
      # submodules from outside GitHub, apparently.
      shell: bash
      run: |
        git submodule init
        git submodule update --recursive

    - name: Create build directory
      shell: bash
      run: |
        mkdir build

    - name: Configure CMake
      shell: bash
      working-directory: build
      run: |
        cmake \
          -DCMAKE_CXX_COMPILER=g++ \
          -DCMAKE_C_COMPILER=gcc \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
          ..
