add_subdirectory("${CMAKE_CURRENT_LIST_DIR}/input")
add_subdirectory("${CMAKE_CURRENT_LIST_DIR}/renderer")
add_subdirectory("${CMAKE_CURRENT_LIST_DIR}/camera")
add_subdirectory("${CMAKE_CURRENT_LIST_DIR}/traits")
add_subdirectory("${CMAKE_CURRENT_LIST_DIR}/log")
add_subdirectory("${CMAKE_CURRENT_LIST_DIR}/time")
add_subdirectory("${CMAKE_CURRENT_LIST_DIR}/config")
add_subdirectory("${CMAKE_CURRENT_LIST_DIR}/util")
add_subdirectory("${CMAKE_CURRENT_LIST_DIR}/dev_ui")
