name: Build

on:
  pull_request:
    branches: [ "dev" ]
    paths:
      - src/**
      - CMakeLists.txt
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  build:
    if: ${{ github.event.pull_request.draft == false }}
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/vis4rd/monoshot:latest
      options: --user 1001 # required for init of submodules, workaround for: https://github.com/actions/runner/issues/2033

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Prepare environment
      id: prepare-env
      uses: ./.github/actions/prepare_env

    - name: Load cache build directory
      uses: actions/cache/restore@v3
      id: restore-cache
      with:
        path: build/
        key: build-gcc-${{ hashFiles('src/**/*') }}
        restore-keys: build-gcc-

    - name: Configure ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: gcc-${{ hashFiles('src/**/*') }}
        restore-keys: gcc-
        verbose: 1
        append-timestamp: false

    - name: Build
      working-directory: build/
      run: |
        cmake --build . --config Release --parallel

    - name: Cache build directory
      uses: actions/cache/save@v3
      with:
        path: build/
        key: ${{ steps.restore-cache.outputs.cache-primary-key }}
