name: Quality

on:
  pull_request:

jobs:
  gitmoji:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: false

    - name: Get commits from pull request
      # Fetch commit messages from the pull request
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        curl -s -H "Authorization: token $GITHUB_TOKEN" \
          "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/commits" \
          | jq -r '.[].commit.message' > commit_messages.txt

    - name: Get all Gitmoji's
      shell: bash
      run: |
        curl -s https://gitmoji.dev/api/gitmojis > gitmoji_spec.json
        cat gitmoji_spec.json | jq '.gitmojis[] | .emoji, .code' > gitmojis.txt

    - name: Check if commit messages contain a Gitmoji
      shell: bash
      run: |
        gitmoji_script="${{ github.workspace }}/.scripts/ensure_commit_starts_with_gitmoji.sh"

        # Set executable permission on the script
        chmod +x $gitmoji_script

        # Check each commit message
        is_ok=true
        while IFS= read -r commit; do
          $gitmoji_script "$commit" gitmojis.txt
          if [[ $? -eq 1 ]]; then
            is_ok=false
            break
          fi
        done < commit_messages.txt

        if [[ $is_ok == false ]]; then
          echo "Commit message does not start with a Gitmoji: '$commit'"
          exit 1
        else
          echo "All commit messages start with a Gitmoji"
        fi
