name: Code Quality

on:
  pull_request:
    branches: [ "dev" ]
    paths:
      - src/**/*.hpp
      - src/**/*.cpp
      - src/**/*.inl
      - src/**/*.c
      - src/**/*.h
      - .clang-tidy
      - .clang-format
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  clang-format:
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/vis4rd/monoshot:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get changed files (for triggering)
        id: changed-files-trigger
        uses: tj-actions/changed-files@v45
        with:
          files: |
            src/**/*.hpp
            src/**/*.cpp
            src/**/*.inl
            src/**/*.c
            src/**/*.h
            .clang-format

      - name: Get changed files (for formatting)
        id: changed-files-format
        uses: tj-actions/changed-files@v45
        if: steps.changed-files-trigger.outputs.any_changed == 'true'
        with:
          files: |
            src/**/*.hpp
            src/**/*.cpp
            src/**/*.inl
            src/**/*.c
            src/**/*.h

      - name: Check code formatting
        if: steps.changed-files-trigger.outputs.any_changed == 'true'
        shell: bash
        run: |
          echo "Files selected for formatting check:"
          echo ${{ steps.changed-files-format.outputs.all_changed_files }}

          clang-format --dry-run --Werror ${{ steps.changed-files-format.outputs.all_changed_files }}

          if [ $? -eq 0 ]; then echo "Code formatting check passed."; exit 0;
          else echo "Code formatting check failed."; exit 1;
          fi

  clang-tidy:
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/vis4rd/monoshot:latest
      options: --user 1001 # required for init of submodules, workaround for: https://github.com/actions/runner/issues/2033

    if: ${{ github.event.pull_request.draft == false }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get changed files (for triggering)
        id: changed-files-trigger
        uses: tj-actions/changed-files@v45
        with:
          files: |
            src/**/*.hpp
            src/**/*.cpp
            src/**/*.inl
            src/**/*.c
            src/**/*.h
            .clang-tidy

      - name: Prepare environment
        id: prepare-env
        uses: ./.github/actions/prepare_env
        if: steps.changed-files-trigger.outputs.any_changed == 'true'

      - name: Run clang-tidy
        if: steps.changed-files-trigger.outputs.any_changed == 'true'
        shell: bash
        run: |
          cmake -P ./cmake/clang-tidy.cmake

  cppcheck:
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/vis4rd/monoshot:latest
      options: --user 1001 # required for init of submodules, workaround for: https://github.com/actions/runner/issues/2033

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get changed files (for triggering)
        id: changed-files-trigger
        uses: tj-actions/changed-files@v45
        with:
          files: |
            src/**/*.hpp
            src/**/*.cpp
            src/**/*.inl
            src/**/*.c
            src/**/*.h

      - name: Run cppcheck
        if: steps.changed-files-trigger.outputs.any_changed == 'true'
        shell: bash
        run: |
          mkdir -p .cache/cppcheck/
          cmake -P ./cmake/cppcheck.cmake
